//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.20.0
//     from Assets/CerebroToque.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/CerebroToque.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CerebroToque: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CerebroToque()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""CerebroToque"",
    ""maps"": [
        {
            ""name"": ""Toque"",
            ""id"": ""34138729-a5f7-4ec0-8d09-e71d22df08d7"",
            ""actions"": [
                {
                    ""name"": ""PrimeiroContato"",
                    ""type"": ""Button"",
                    ""id"": ""d3bf37e9-049b-4f46-9ad5-b38132b287b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""PrimeiraPos"",
                    ""type"": ""Value"",
                    ""id"": ""c12bff3b-aea7-4242-a5bc-6e2d407e83a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f1c7cb13-7e65-4c06-8c39-cb896a97b216"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimeiroContato"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16730fd6-e6f8-407d-88c9-b1510a989f97"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimeiraPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Toque
        m_Toque = asset.FindActionMap("Toque", throwIfNotFound: true);
        m_Toque_PrimeiroContato = m_Toque.FindAction("PrimeiroContato", throwIfNotFound: true);
        m_Toque_PrimeiraPos = m_Toque.FindAction("PrimeiraPos", throwIfNotFound: true);
    }

    ~@CerebroToque()
    {
        UnityEngine.Debug.Assert(!m_Toque.enabled, "This will cause a leak and performance issues, CerebroToque.Toque.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Toque
    private readonly InputActionMap m_Toque;
    private List<IToqueActions> m_ToqueActionsCallbackInterfaces = new List<IToqueActions>();
    private readonly InputAction m_Toque_PrimeiroContato;
    private readonly InputAction m_Toque_PrimeiraPos;
    /// <summary>
    /// Provides access to input actions defined in input action map "Toque".
    /// </summary>
    public struct ToqueActions
    {
        private @CerebroToque m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ToqueActions(@CerebroToque wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Toque/PrimeiroContato".
        /// </summary>
        public InputAction @PrimeiroContato => m_Wrapper.m_Toque_PrimeiroContato;
        /// <summary>
        /// Provides access to the underlying input action "Toque/PrimeiraPos".
        /// </summary>
        public InputAction @PrimeiraPos => m_Wrapper.m_Toque_PrimeiraPos;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Toque; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ToqueActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ToqueActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ToqueActions" />
        public void AddCallbacks(IToqueActions instance)
        {
            if (instance == null || m_Wrapper.m_ToqueActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ToqueActionsCallbackInterfaces.Add(instance);
            @PrimeiroContato.started += instance.OnPrimeiroContato;
            @PrimeiroContato.performed += instance.OnPrimeiroContato;
            @PrimeiroContato.canceled += instance.OnPrimeiroContato;
            @PrimeiraPos.started += instance.OnPrimeiraPos;
            @PrimeiraPos.performed += instance.OnPrimeiraPos;
            @PrimeiraPos.canceled += instance.OnPrimeiraPos;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ToqueActions" />
        private void UnregisterCallbacks(IToqueActions instance)
        {
            @PrimeiroContato.started -= instance.OnPrimeiroContato;
            @PrimeiroContato.performed -= instance.OnPrimeiroContato;
            @PrimeiroContato.canceled -= instance.OnPrimeiroContato;
            @PrimeiraPos.started -= instance.OnPrimeiraPos;
            @PrimeiraPos.performed -= instance.OnPrimeiraPos;
            @PrimeiraPos.canceled -= instance.OnPrimeiraPos;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ToqueActions.UnregisterCallbacks(IToqueActions)" />.
        /// </summary>
        /// <seealso cref="ToqueActions.UnregisterCallbacks(IToqueActions)" />
        public void RemoveCallbacks(IToqueActions instance)
        {
            if (m_Wrapper.m_ToqueActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ToqueActions.AddCallbacks(IToqueActions)" />
        /// <seealso cref="ToqueActions.RemoveCallbacks(IToqueActions)" />
        /// <seealso cref="ToqueActions.UnregisterCallbacks(IToqueActions)" />
        public void SetCallbacks(IToqueActions instance)
        {
            foreach (var item in m_Wrapper.m_ToqueActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ToqueActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ToqueActions" /> instance referencing this action map.
    /// </summary>
    public ToqueActions @Toque => new ToqueActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Toque" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ToqueActions.AddCallbacks(IToqueActions)" />
    /// <seealso cref="ToqueActions.RemoveCallbacks(IToqueActions)" />
    public interface IToqueActions
    {
        /// <summary>
        /// Method invoked when associated input action "PrimeiroContato" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimeiroContato(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimeiraPos" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimeiraPos(InputAction.CallbackContext context);
    }
}
